### ISSUE TITLE
Issues when submitting form and conflict with Bugsnag gem

### ISSUE THREAD

**Issue by spence-man** [markets/invisible_captcha#76] opened 2020-09-01 00:03 UTC
invisible_captcha (1.0.1)
ruby 2.6.4p104
rails (6.0.3.2)
bugsnag (6.12.1)

Been having issues with submitting the form with the invisible captcha.  The invisible captcha gem was working at one point but then an error started appearing. For testing, I submit the form and fill in the hidden field to act as a bot. 

Here's the console return

```
Started POST "/contact-us" for ::1 at 2020-08-31 16:44:19 -0700
Processing by PublicController#contact_form as JS
  Parameters: {"authenticity_token"=>"redacted", "contact"=>{"name"=>"asdf asdf", "email"=>"spam@test.com", "phone"=>"17145551234", "message"=>"asdf"}, "subtitle"=>"This is spam", "commit"=>"Send"}
Potential spam detected for IP ::1. Invisible Captcha honeypot param 'subtitle' was present.
[SPAM] {:message=>"Invisible Captcha honeypot param 'subtitle' was present.", :remote_ip=>"::1", :user_agent=>"redacted", :controller=>"public", :action=>"contact_form", :url=>"http://localhost:3000/contact-us", :params=>{"authenticity_token"=>"redacted==", "contact"=>{"name"=>"Test Name", "email"=>"spam@test.com", "phone"=>"15553334444", "message"=>"test message"}, "subtitle"=>"This is spam", "commit"=>"Send", "controller"=>"public", "action"=>"contact_form"}}
Breadcrumb Controller halted via callback meta_data filter:Proc has been dropped for having an invalid data type
Filter chain halted as #<Proc:0x00007ffa1c687d10@/Users/spencermandzik/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/invisible_captcha-1.0.1/lib/invisible_captcha/controller_ext.rb:7> rendered or redirected
Completed 200 OK in 1ms (ActiveRecord: 0.0ms | Allocations: 527)
```

Looks like in Bugsnag this is where the output is coming from:
https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/breadcrumbs/validator.rb#L23

I'll also contact Bugsnag to see if this is also something on there end as well.

**Comment by markets** [comment] 2020-09-01 09:27
Hi @spence-man, sorry I dont understand what kind of problem is caused by `invisible_captcha` in combination with `bugsnag` (never used that service/gem, so I have no idea what means the line of code you pasted above). All code related to the controllers layer, in this gem, [is here](https://github.com/markets/invisible_captcha/blob/master/lib/invisible_captcha/controller_ext.rb)... in case you want to take a look and try to understand the "incompatibility" with `bugsnag`.

Best,
Marc

**Comment by markets** [comment] 2020-10-06 22:05
I'm gonna close this one. Please re-open in case you finally can confirm the issue is caused by `invisible_captcha`. Thanks.

**Closed by markets** 2020-10-06 22:05 UTC
Labels: invalid, question
